pull_request_rules:
  - name: Dependabot
    conditions:
      - "status-success=unit-bdd-tests-and-scan-dependencies"
      - base=main
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      merge:
        method: rebase
