# Python to Linux Web App on Azure
# Build your Python project and deploy it to Azure as a Linux Web App.
# Change python version to one thats appropriate for your application.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  - main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: "0c9df823-c46e-48c7-aead-8da6f31a0926"
  # Agent VM image name
  vmImageName: "ubuntu-latest"
  # Environment name
  environmentName: "Test"
  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)
  # Python version: 3.9
  pythonVersion: "3.9"

stages:
  - stage: LintAndVulnerabilityScanning
    displayName: LintAndVulnerabilityScanning
    jobs:
      - job: LintAndVulnerabilityScanning
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "$(pythonVersion)"
            displayName: "Use Python $(pythonVersion)"
          - script: |
              curl -sSL https://install.python-poetry.org | python3 -
              echo "export PATH"="/home/hukadmin/.local/bin:$PATH">>~/.bashrc
              source ~/.bashrc
              make activate
              make install
            workingDirectory: $(projectRoot)
            displayName: "Install Poetry and Dependencies"
          - script: |
              make format-lint
            workingDirectory: $(projectRoot)
            displayName: "Format Lint"
          - script: |
              make sast
            workingDirectory: $(projectRoot)
            displayName: "Static Analysis"
          - script: |
              make dependency-vulnerability-scan
            workingDirectory: $(projectRoot)
            displayName: "Dependency Vulnerability Scan"
  - stage: Test
    displayName: Testing
    jobs:
      - job: Testing
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "$(pythonVersion)"
            displayName: "Use Python $(pythonVersion)"
          - script: |
              curl -sSL https://install.python-poetry.org | python3 -
              echo "export PATH"="/home/hukadmin/.local/bin:$PATH">>~/.bashrc
              source ~/.bashrc
              make activate
              make install
            workingDirectory: $(projectRoot)
            displayName: "Install Poetry and Dependencies"
          - script: |
              make unit-test
            workingDirectory: $(projectRoot)
            displayName: "Unit Testing"
          - script: |
              make mutation-testing
            workingDirectory: $(projectRoot)
            displayName: "Mutation Testing"
          - script: |
              make bdd-test
            workingDirectory: $(projectRoot)
            displayName: "BDD Test"
