# resource_types:
#   - name: build-metadata
#     type: docker-image
#     source:
#       repository: swce/metadata-resource

resources:
  - name: source-repo
    type: git
    icon: github
    source:
      branch: main
      uri: https://github.com/abhisheksr01/zero-2-hero-python-flask-microservice.git
  # - name: build-metadata
  #   type: build-metadata
  - name: py-poetry
    type: registry-image
    source:
      repository: abhisheksr01/py-poetry
      tag: latest
  # - name: concourse-dcind-image
  #   icon: docker
  #   type: registry-image
  #   source:
  #     repository: karlkfi/concourse-dcind
  # - name: helm
  #   icon: docker
  #   type: registry-image
  #   source:
  #     repository: abhisheksr01/eks-helm
  #     tag: latest
  # - name: alpine
  #   type: registry-image
  #   source:
  #     repository: abhisheksr01/alpine
  #     tag: latest
  # - name: zap
  #   type: registry-image
  #   source:
  #     repository: owasp/zap2docker-stable
  #     tag: latest
  # - name: loadimpact-k6
  #   type: registry-image
  #   source:
  #     repository: loadimpact/k6
  #     tag: latest

jobs:
  - name: format-lint
    plan:
      - get: source-repo
        trigger: true
      - get: py-poetry
      - task: check-format-lint
        file: source-repo/concourse-ci/tasks/poetry/task.yml
        image: py-poetry
        params:
          TARGET: format-lint
  - name: static-application-security-testing
    plan:
      - get: source-repo
        trigger: true
      - get: py-poetry
      - task: check-format-lint
        file: source-repo/concourse-ci/tasks/poetry/task.yml
        image: py-poetry
        params:
          TARGET: sast
  - name: dependency-vulnerability-scan
    plan:
      - get: source-repo
        trigger: true
      - get: py-poetry
      - task: check-format-lint
        file: source-repo/concourse-ci/tasks/poetry/task.yml
        image: py-poetry
        params:
          TARGET: dependency-vulnerability-scan
  - name: unit-testing-and-code-coverage
    plan:
      - get: source-repo
        trigger: true
      - get: py-poetry
      - task: check-format-lint
        file: source-repo/concourse-ci/tasks/poetry/task.yml
        image: py-poetry
        params:
          TARGET: unit-test
  - name: bdd-e2e-testing
    plan:
      - get: source-repo
        trigger: true
      - get: py-poetry
      - task: check-format-lint
        file: source-repo/concourse-ci/tasks/poetry/task.yml
        image: py-poetry
        params:
          TARGET: bdd-test
  - name: mutation-testing
    plan:
      - get: source-repo
        trigger: true
      - get: py-poetry
      - task: check-format-lint
        file: source-repo/concourse-ci/tasks/poetry/task.yml
        image: py-poetry
        params:
          TARGET: mutation-testing