resource_types:
  - name: build-metadata
    type: docker-image
    source:
      repository: swce/metadata-resource

resources:
  - name: source-repo
    type: git
    icon: github
    source:
      branch: main
      uri: https://github.com/abhisheksr01/zero-2-hero-python-flask-microservice.git
  - name: build-metadata
    type: build-metadata
  - name: py-poetry
    type: registry-image
    source:
      repository: abhisheksr01/py-poetry
      tag: latest
  - name: concourse-dcind-image
    icon: docker
    type: registry-image
    source:
      repository: karlkfi/concourse-dcind
  - name: helm
    icon: docker
    type: registry-image
    source:
      repository: abhisheksr01/eks-helm
      tag: latest
  - name: alpine
    type: registry-image
    source:
      repository: abhisheksr01/alpine
      tag: latest
  - name: zap
    type: registry-image
    source:
      repository: owasp/zap2docker-stable
      tag: latest
  - name: loadimpact-k6
    type: registry-image
    source:
      repository: loadimpact/k6
      tag: latest

jobs:
  - name: format-lint
    plan:
      - get: source-repo
        trigger: true
      - get: py-poetry
      - task: black-format-flake8-lint
        file: source-repo/concourse-ci/tasks/poetry/task.yml
        image: py-poetry
        params:
          TARGET: format-lint
  - name: static-application-security-testing
    plan:
      - get: source-repo
        trigger: true
      - get: py-poetry
      - task: bandit-sast
        file: source-repo/concourse-ci/tasks/poetry/task.yml
        image: py-poetry
        params:
          TARGET: sast
  - name: dependency-vulnerability-scan
    plan:
      - get: source-repo
        trigger: true
      - get: py-poetry
      - task: safety-dependency-vulnerability-scan
        file: source-repo/concourse-ci/tasks/poetry/task.yml
        image: py-poetry
        params:
          TARGET: dependency-vulnerability-scan
  - name: unit-testing-and-code-coverage
    plan:
      - get: source-repo
        trigger: true
        passed:
          - format-lint
          - static-application-security-testing
          - dependency-vulnerability-scan
      - get: py-poetry
      - task: pytest-unit-test
        file: source-repo/concourse-ci/tasks/poetry/task.yml
        image: py-poetry
        params:
          TARGET: unit-test
  - name: bdd-e2e-testing
    plan:
      - get: source-repo
        trigger: true
        passed:
          - format-lint
          - static-application-security-testing
          - dependency-vulnerability-scan
      - get: py-poetry
      - task: behave-bdd-test
        file: source-repo/concourse-ci/tasks/poetry/task.yml
        image: py-poetry
        params:
          TARGET: bdd-test
  - name: mutation-testing
    plan:
      - get: source-repo
        trigger: true
        passed:
          - format-lint
          - static-application-security-testing
          - dependency-vulnerability-scan
      - get: py-poetry
      - task: mutmut-mutation-testing
        file: source-repo/concourse-ci/tasks/poetry/task.yml
        image: py-poetry
        params:
          TARGET: mutation-testing
  - name: docker-build-scan-push
    plan:
    - get: source-repo
      trigger: true
      passed:
        - unit-testing-and-code-coverage
        - bdd-e2e-testing
        - mutation-testing
    - get: concourse-dcind-image
    - get: build-metadata
    - task: build-image
      privileged: true
      file: source-repo/concourse-ci/tasks/docker/build-image.yml
      image: concourse-dcind-image
      params:
        DOCKER_USER : ((docker_user))
        DOCKER_PASS : ((docker_pass))
        DOCKER_IMAGE : ((docker_image))
  - name: k8s-deploy
    plan:
    - get: source-repo
      trigger: true
      passed:
        - docker-build-scan-push
    - get: helm
    - task: app-helm-deploy
      privileged: true
      file: source-repo/concourse-ci/tasks/helm/helm-deployment.yml
      image: helm
      params:
        EKS_CLUSTER_NAME: ((eks_cluster_name))
        AWS_DEFAULT_REGION: ((aws_default_region))
        EKS_NAMESPACE: ((eks_namespace))
        RELEASE_NAME: ((release_name))
        AWS_ACCESS_KEY_ID: ((aws_access_key_id))
        AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
  # Example of how can we execute a job with inline commands rather than task files
  - name: health-check
    plan:
    - get: source-repo
      trigger: true
      passed:
        - k8s-deploy
    - get: alpine
    - task: health-check
      params:
        ROOT_ENDPOINT: ((root_endpoint))
      image: alpine
      config:
        platform: linux
        inputs:
          - name: source-repo
        run:
          path: /bin/sh
          args:
            - -c
            - |
              ./source-repo/scripts/health-check.sh
  - name: penetration-test
    plan:
      - get: source-repo
        trigger: true
        passed:
          - k8s-deploy
      - get: zap
      - task: pen-test
        image: zap
        params:
          ROOT_ENDPOINT: ((root_endpoint))
        config:
          platform: linux
          inputs:
            - name: source-repo
          run:
            path: bash
            args:
              - -c
              - |
                cd ../../../../zap/
                echo "Performing Penetration test on Base URL : ${ROOT_ENDPOINT}"
                mkdir wrk && zap-baseline.py -T 5 -w report.md -a -j -t "${ROOT_ENDPOINT}" | while read -r line; do if echo "${line}" | grep -q "FAIL-NEW: [0-9]+[\t ]+FAIL-INPROG: [0-9]+[\t ]+WARN-NEW: [0-9]+[\t ]+WARN-INPROG: [0-9]+[\t ]+INFO: [0-9]+[\t ]+IGNORE: [0-9]+[\t ]+PASS: [0-9]+" ; then pidof Xvfb | xargs -r kill ; fi ; echo "${line}" ; done
                EXIT_CODE="${?}"
                cat /zap/wrk/report.md
                pidof Xvfb | xargs -r kill
                exit "${EXIT_CODE}"
  - name: load-performance-test
    plan:
      - get: source-repo
        trigger: true
        passed:
          - k8s-deploy
      - get: loadimpact-k6
      - task: load-test
        params:
          ROOT_ENDPOINT: ((root_endpoint))
        image: loadimpact-k6
        config:
          platform: linux
          inputs:
            - name: source-repo
          run:
            path: /bin/sh
            args:
              - -c
              - |
                cd source-repo/performance-testing
                LOAD_TEST_URL="${ROOT_ENDPOINT}/greetings/abhishek"
                echo "Starting load performance test on ${LOAD_TEST_URL}"
                k6 run -e ROOT_ENDPOINT="${LOAD_TEST_URL}" -u 50 -d 10s script.js
                echo "Completed load performance test"
  - name: acceptance-testing
    plan:
      - get: source-repo
        trigger: true
        passed:
          - k8s-deploy
      - get: py-poetry
      - task: acceptance-testing
        file: source-repo/concourse-ci/tasks/poetry/task.yml
        image: py-poetry
        params:
          TARGET: acceptance-test
          ROOT_ENDPOINT: ((root_endpoint))