---
platform: linux

inputs:
- name: source-repo

run:
  path: bash
  args:
    - -cu
    - |
      set -e
      echo "starting helm deploying....."
      cd source-repo/
      aws eks --region ${AWS_DEFAULT_REGION} update-kubeconfig --name ${EKS_CLUSTER_NAME}
      ./scripts/helm-deploy.sh