# This workflow will install Python dependencies using poetry, run unit , bdd tests and scan for the vulnerabilities in the dependencies
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: unit, bdd tests & scan dependencies

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  unit-bdd-tests-and-scan-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        pip install --user poetry
        poetry install
    - name: Run Unit Test
      run: |
        make unit-test
    - name: Run BDD Test
      run: |
        make bdd-test
    - name: Dependency vulnerability scan
      run: |
        make dependency-vulnerability-scan
